import { PatientCase, CaseStatus } from './types';

export const initialCases: PatientCase[] = [
  { id: "1", pjs: "Manuel Burga", ciudad: "Lambayeque", fechaIngreso: "2025/01", medico: "Rodrigo Auqui", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Almanzor", dispensacion: "Essalud Chiclayo", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "2", pjs: "Alejandra Chura", ciudad: "Cusco", fechaIngreso: "2025/01", medico: "Ramiro Tupayachi", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Cusco", dispensacion: "Essalud Cusco", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "3", pjs: "Manuel Burga", ciudad: "La Libertad", fechaIngreso: "2025/02", medico: "Paulo Castañeda", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Alta Complejidad", dispensacion: "Essalud Chiclayo", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "4", pjs: "Manuel Burga", ciudad: "La Libertad", fechaIngreso: "2025/02", medico: "Claudia Chavez", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Alta Complejidad", dispensacion: "Essalud Alta Complejidad", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "5", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/02", medico: "José Negrón", aseguradora: "Saludpol", sector: "Privado", institucion: "Hospital Policía", dispensacion: "IPOR", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "6", pjs: "Yvette Morilla", ciudad: "Lima", fechaIngreso: "2025/03", medico: "Hugo Fuentes", aseguradora: "Rímac", sector: "Privado", institucion: "Sanna Aliada", dispensacion: "Cuida", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "7", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/03", medico: "Henry Gomez", aseguradora: "Rímac", sector: "Privado", institucion: "Oncosalud", dispensacion: "Cuida", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "8", pjs: "Alejandra Chura", ciudad: "Cusco", fechaIngreso: "2025/03", medico: "Martin Gutiérrez", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Cusco", dispensacion: "Essalud Cusco", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "9", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/03", medico: "George Oblitas", aseguradora: "Particular", sector: "Privado", institucion: "UOM", dispensacion: "Life&Hope", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "10", pjs: "Yvette Morilla", ciudad: "Lima", fechaIngreso: "2025/03", medico: "Miguel Ticona", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Rebagliati", dispensacion: "Essalud Rebagliati", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "11", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/03", medico: "Pilar Milla", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Almenara", dispensacion: "Essalud Almenara", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "12", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/04", medico: "Yesenia Ramírez", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Almenara", dispensacion: "Essalud Almenara", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "13", pjs: "Yvette Morilla", ciudad: "Lima", fechaIngreso: "2025/05", medico: "Patricia Pimentel", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Sabogal", dispensacion: "Essalud Sabogal", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "14", pjs: "Yvette Morilla", ciudad: "Lima", fechaIngreso: "2025/05", medico: "Miguel Ticona", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Rebagliati", dispensacion: "Essalud Rebagliati", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "15", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/05", medico: "Pilar Milla", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Almenara", dispensacion: "Essalud Almenara", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "16", pjs: "Alejandra Chura", ciudad: "Arequipa", fechaIngreso: "2025/05", medico: "Oscar Carnero", aseguradora: "Pacífico", sector: "Privado", institucion: "Auna AQP", dispensacion: "Auna AQP", distribuidor: "Quimica Suiza", indicacion: "QSDB04", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "17", pjs: "Manuel Burga", ciudad: "Lambayeque", fechaIngreso: "2025/05", medico: "Paul Galvan", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Almanzor", dispensacion: "Essalud Chiclayo", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "18", pjs: "Mariana Braschi", ciudad: "Lima", fechaIngreso: "2025/05", medico: "Henry Gomez", aseguradora: "Oncosalud", sector: "Privado", institucion: "Oncosalud", dispensacion: "Oncosalud", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "19", pjs: "Yvette Morilla", ciudad: "Lima", fechaIngreso: "2025/05", medico: "Edgardo Salinas", aseguradora: "Seguridad Social", sector: "Público", institucion: "Essalud Rebagliati", dispensacion: "Essalud Rebagliati", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO },
  { id: "20", pjs: "Yvette Morilla", ciudad: "Lima", fechaIngreso: "2025/06", medico: "Carlos Farfán", aseguradora: "Rímac", sector: "Privado", institucion: "Clinica Internacional", dispensacion: "Cuida", distribuidor: "Quimica Suiza", indicacion: "QSDB03", dosis: "Enhertu100mg", status: CaseStatus.ACTIVO }
];